.TH UNTITLED 9 "" "Vendor Name" "User Commands"
.ad l
.nh
.SH "GREEN 1 'JULY 2012' 'DEBIAN GNU / LINUX' 'USER MANUALS'"
.SS NAME
green - a lightweight PDF reader for the Framebuffer using libpoppler
.SS SYNOPSIS
\fBgreen\fR [\fBoptions\fR] <\fBPDF file 1\fR> \fI[PDF file 2]\fR ...
.SS DESCRIPTION
\fBgreen\fR is meant to be a light PDF reader for the Linux Framebuffer. 
However, it can also be used inside a graphical X11 Session like GNOME or
MATE.
.PP
\fBgreen\fR features:
.IP " \[bu] " 3
uses libpoppler for PDF reading
.IP " \[bu] " 3
uses SDL to support various frontends (including framebuffer)
.IP " \[bu] " 3
multiple documents
.IP " \[bu] " 3
single page mode
.IP " \[bu] " 3
fit width, height or page
.IP " \[bu] " 3
zooming
.IP " \[bu] " 3
goto page
.IP " \[bu] " 3
search function
.IP " \[bu] " 3
scheme support
.SS OPTIONS
\fB-b\fR
Do not write "busy" to stdout while processing.
.PP
\fB-c\fR \fIconfig-file\fR
Use the alternate system wide \fIconfig-file\fR instead of \fI/etc/foo.conf\fR. This
overrides any \fBFOOCONF\fR environment variable.
.PP
\fB-a\fR
In addition to the baz segments, also parse the blurfl headers.
.PP
\fB-r\fR
Recursive mode. Operates as fast as lightning at the expense of a megabyte
of virtual memory.
.SS "PROGRAM OPERATION"
\fB<TAB>\fR - Go to the next open document.
\fB<F<n>>\fR - Go to the n-th document.
\fBESC\fR - Escape current input mode.  
\fBq\fR - Quit
.SS "NAVIGATION INSIDE A DOCUMENT"
\fB<h, left arrow>\fR - Scroll left.
\fB<l, right arrow>\fR - Scroll right.
\fB<j, down arrow>\fR - Scroll down.
\fB<k, up arrow>\fR - Scroll up.
\fB<pg up>\fR - Go to previous page.
\fB<pg dn>\fR - Go to next page.
\fB<g<n>RETURN>\fR - Go to page n.
\fB<+,->\fR - Zoom in, Zoom out.
.SS FILES
\fI$(HOME)/.green.conf\fR 
Per user configuration file.
\fI/usr/local/etc/green.conf\fR
The system wide configuration file.
.SS AUTHOR
The Green source code may be downloaded from http://github.com/schandinat/green/.                      
Green is Licensed under GNU GPL version 3.  
This man page was written for the Debian GNU / Linux System by Oz Nahum nahumoz@gmail.com.
