.TH GREEN 1 "JULY 2012"
.SH NAME
green - a lightweight PDF reader for the Framebuffer using libpoppler
.SH SYNOPSIS
\fBgreen\fR [\fIoptions\fR] <\fIPDF file 1\fR> \fI[PDF file 2]\fR ...
.SH DESCRIPTION
\fBgreen\fR is meant to be a light PDF reader for the Linux Framebuffer. 
However, it can also be used inside a graphical X11 Session like GNOME or
MATE.
.PP
\fBgreen\fR features:
.IP " \[bu] " 3
uses libpoppler for PDF reading
.IP " \[bu] "
uses SDL to support various frontends (including framebuffer)
.IP " \[bu] "
multiple documents
.IP " \[bu] "
single page mode
.IP " \[bu] "
fit width, height or page
.IP " \[bu] "
zooming
.IP " \[bu] "
goto page
.IP " \[bu] "
search function
.IP " \[bu] "
scheme support
.SH OPTIONS
.TP
\fB-config\fP=\fIfile\fP
use an alternate configuration file instead of \fI/etc/green.conf\fP
.TP
\fB-fit\fP=(\fInone|width|height|page\fP)
fit image to display
.TP
\fB-width\fP=\fInum\fP
start with a window large \fInum\fP pixels
.TP
\fB-height\fP=\fInum\fp
start with a window \fInum\fP pixels tall
.TP
\fB-pixelheight=\fInum\fP
set the height of a pixel as a proportion to its width
.TP
\fB-palettehack\fP
use an hack that speeds up drawing on an 8-bit palette display but may be
incorrect
.TP
\fB-altvt\fP
switch to previous/next virtual terminal by alt- and alt+
.TP
\fB-nomouse\fP
disable mouse; equivalent to setting "Mouse=0" in the current scheme or
SDL_NOMOUSE=1 in the environment
.TP
\fB-fullscreen\fP
.PD 0
.TP
\fB-nofullscreen\fP
.PD
start in fullscreen mode or not
.TP
\fB-scheme\fP=\fI<id list>\fp
select a different scheme.
.SH PROGRAM OPERATION
\fB<TAB>\fR - Go to the next open document.
.br
\fB<F<n>>\fR - Go to the n-th document.
.br
\fBESC\fR - Escape current input mode.  
.br
\fBq\fR - Quit
.SS Navigation inside a document
\fBh, left arrow\fR - Scroll left.
.br
\fBl, right arrow\fR - Scroll right.
.br
\fBj, down arrow\fR - Scroll down.
.br
\fBk, up arrow\fR - Scroll up.
.br
\fB.\fR - Center page.
.br
\fBrr, rl\fR - Rotate right, rotate left.
.br
\fBpg up\fR - Go to previous page.
.br
\fBpg dn\fR - Go to next page.
.br
\fBg<n>RETURN\fR - Go to page n.
.br
\fB+,-\fR - Zoom in, Zoom out.
.SS Fitting
\fBfn\fP - disable page fitting mode.
.br
\fBfw\fP - fit page width.
.br
\fBfh\fP - fit page height.
.br
\fBfp\fP - fit whole page.
.SS Searching 
\fBs<X><RETURN>\fP - Start search for string X.
.br
\fBn\fP - Show next result.
.SH FILES
\fI$(HOME)/.green.conf\fR 
Per user configuration file.
.br
\fI/etc/green.conf\fR
The system wide configuration file.
.SH EXAMPLE CONFIGURATION FILE
.nf
# green configuration file
#
# add to .bashrc:
# [ "$TERM" == linux ] && alias green='green -scheme=fb'

# scheme for a 600x400 framebuffer
SCHEME fb
{
	Fit=width
	Pixelheight=1.2
	Altvt=yes
	Mouse=0
	Palettehack=1
}

# scheme for X11
SCHEME x11
{
	Width=800
	Height=600
}

# default scheme
DEFAULT_SCHEME x11
.fi
.SH AUTHOR
The Green source code may be downloaded from
http://github.com/schandinat/green/.                      

Green is Licensed under GNU GPL version 3.  

This man page was written for the Debian GNU / Linux System by Oz Nahum
nahumoz@gmail.com.

